<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7680" started-at="2017-05-09T14:07:13Z" finished-at="2017-05-09T14:07:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7680" started-at="2017-05-09T14:07:13Z" finished-at="2017-05-09T14:07:21Z">
      <class name="com.vector.func.smoketest">
        <test-method status="FAIL" signature="verifytitle()[pri:0, instance:com.vector.func.smoketest@f6c48ac]" name="verifytitle" duration-ms="3131" started-at="2017-05-09T19:37:13Z" finished-at="2017-05-09T19:37:16Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.relevantcodes.extentreports.ExtentTest.isPathRelative(ExtentTest.java:502)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCapture(ExtentTest.java:287)
	at com.vector.func.reporting.addstep(reporting.java:34)
	at com.vector.func.smoketest.verifytitle(smoketest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifytitle -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:com.vector.func.smoketest@f6c48ac]" name="teardown" is-config="true" duration-ms="4526" started-at="2017-05-09T19:37:16Z" finished-at="2017-05-09T19:37:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifytitle status=FAILURE method=smoketest.verifytitle()[pri:0, instance:com.vector.func.smoketest@f6c48ac] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.vector.func.smoketest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
